### PR TITLE
Prince/ added temporary static spacing values

### PR DESCRIPTION
**Pull request by prince-deriv**
- added temporary spacing values to be replaced later once figma designs are all connected to `Quill Tokens`

### CODE REVIEW

**Review by markwylde-deriv — CHANGES_REQUESTED** [review]
Can we make this really clear it shouldn't be used. Something like `--TEMP_static-spacing-1`, `--NONSTANDARD_static-spacing-1`.

**Review by jia-deriv — APPROVED** [review]

**Comment by prince-deriv** [comment]
> Can we make this really clear it shouldn't be used. Something like `--TEMP_static-spacing-1`, `--NONSTANDARD_static-spacing-1`.

sure @markwylde-deriv

**Review by meenakshi-deriv — APPROVED** [review]

**Review by markwylde-deriv — COMMENTED** [review]
How come we are committing the quill.css into the repo. Shouldn't it be considered a "binary" or "build", and therefore be in a `dist` folder and gitignored?

**Comment by prince-deriv** [comment]
> How come we are committing the quill.css into the repo. Shouldn't it be considered a "binary" or "build", and therefore be in a `dist` folder and gitignored?

@markwylde-deriv  technically yes, but we kept it added so that we can check the history of changes, this will allow us to identify if the new token changes/updates will break stuff.

**Pull request merged**
